#!/bin/sh

if [ "$NODE_ENV" = "production" ]; then
  BABEL_ENV="production"
else
  BABEL_ENV="development"
fi

echo "Build Assets..."
yarn run build:assets

echo "Build Server..."
yarn run build:server

echo "Build Client..."
yarn run build:client

