#!/bin/sh

echo "Build Assets..."
yarn run build:assets > /dev/null

echo "Build Server..."
yarn run build:server > /dev/null

if [ "$NODE_ENV" = "production" ]; then
  echo "Build Client..."
  yarn run build:client > /dev/null
fi

echo "Start Server..."
node lib/server/index.js

