#!/bin/sh

if [ "$NODE_ENV" = "production" ]; then
  BABEL_ENV="production"
else
  BABEL_ENV="development"
fi

echo "Build Assets..."
npm run build:assets > /dev/null

echo "Build Server..."
npm run build:server > /dev/null

if [ "$NODE_ENV" = "production" ]; then
  echo "Build Client..."
  npm run build:client > /dev/null
fi

echo "Start Server..."
node lib/server/index.js

